name: Run Graphistry Challenge

on:
  push:
    branches:
      - main 

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run analysis
        run: python analysis.py

      - name: Show analysis outputs
        run: |
          echo "=== Analysis Summary ==="
          cat analysis_summary.csv
          echo ""
          echo "=== Event Log ==="
          cat investigation_log.txt

